feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

dummyjson:
  basePath: https://dummyjson.com
  uri:
    products: /products